apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: bookmedik
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmedik
      type: database
  template:
    metadata:
      labels:
        app: bookmedik
        type: database
    spec:
      containers:
        - name: contenedor-mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: bookmedik
                  key: USER_BOOKMEDIK
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bookmedik
                  key: BD_BOOKMEDIK
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookmediksecret
                  key: PASS_BOOKMEDIK
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookmediksecret
                  key: root
          volumeMounts:
            - name: mariadb-vol
              mountPath: "/var/lib/mysql"
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mariadb-pvc
